# Generated by Django 4.0.6 on 2024-03-18 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='creation',
            new_name='datadecriacao',
        ),
        migrations.RenameField(
            model_name='musica',
            old_name='spotify',
            new_name='spotify_link',
        ),
    ]
