# Generated by Django 4.0.6 on 2024-03-18 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_rename_creation_album_datadecriacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='banda',
        ),
        migrations.RemoveField(
            model_name='album',
            name='datadecriacao',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='album',
        ),
        migrations.RemoveField(
            model_name='musica',
            name='spotify_link',
        ),
    ]
