# Generated by Django 4.0.6 on 2024-03-18 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_album_datadecriacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='datadecriacao',
            new_name='dataDeCriacao',
        ),
        migrations.AddField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bandas.banda'),
        ),
        migrations.AddField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bandas.album'),
        ),
        migrations.AddField(
            model_name='musica',
            name='spotify_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
